name: Check Semantic PR
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    uses: reqstool/.github/.github/workflows/check-semantic-pr.yml@main
